version: "3.1"

services:
  app:
    image: node:7.10
    command: bash -c "npm install && npm run dev"
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3000:3000
  mongo:
    image: mongo:3.5